version: "3.8"
services:
  app:
    image: galahade/future-trade-docker:v1.2
    working_dir: /app
    networks:
      - future_trading
    depends_on:
      - mongo
    environment:
      MONGO_CONF_FILE: /run/secrets/mongo_conf_file
      TQ_CONF_FILE: /run/secrets/tq_conf_file
      ROHON_CONF_FILE: /run/secrets/rohon_conf_file
      ACCOUNT_TYPE: 0
      ENV_NAME: prod
    secrets:
      - mongo_conf_file
      - tq_conf_file
      - rohon_conf_file
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - trade-mongo-data:/data/db
    networks:
      - future_trading
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
volumes:
  trade-mongo-data:
networks:
  future_trading:
secrets:
  mongo_conf_file:
    file: secrets/mongo_config.yaml
  tq_conf_file:
    file: secrets/tq_config.yaml
  rohon_conf_file:
    file: secrets/rohon_config.yaml
