version: "3.8"
services:
  app:
    image: galahade/future-trade-dev:latest
    working_dir: /app
    volumes:
      - ".:/app"
    environment:
      MONGO_CONF_FILE: /run/secrets/mongo_conf_file
      TQ_CONF_FILE: /run/secrets/tq_conf_file
      ROHON_CONF_FILE: /run/secrets/rohon_conf_file
      ACCOUNT_TYPE: 0
      ENV_NAME: backtest
    secrets:
      - mongo_conf_file
      - tq_conf_file
      - rohon_conf_file
    command: python3 main.py -t -s 2018 -m 1 -e 2022 -tt 2
volumes:
  trade-mongo-data:
networks:
  default:
    name: backtest-db_database
    external: true
secrets:
  mongo_conf_file:
    file: secrets/mongo_config.yaml
  tq_conf_file:
    file: secrets/tq_config.yaml
  rohon_conf_file:
    file: secrets/rohon_config.yaml
