version: "3.8"
services:
  app:
    image: galahade/future-trade-test:latest
    working_dir: /app
    volumes:
      - future-trade-log-data:/log
    depends_on:
      - mongo
    networks:
      - database
    environment:
      MONGO_CONF_FILE: /run/secrets/mongo_conf_file
      TQ_CONF_FILE: /run/secrets/tq_conf_file
      ROHON_CONF_FILE: /run/secrets/rohon_conf_file
      ACCOUNT_TYPE: 0
      ACCOUNT_BALANCE: 200000
      ENV_NAME: test
    secrets:
      - mongo_conf_file
      - tq_conf_file
      - rohon_conf_file
  mongo_main:
    image: mongo
    ports:
      - 27010:27017
    networks:
      - database
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
volumes:
  mongo-data:
  future-trade-log-data:
    external: true
secrets:
  mongo_conf_file:
    file: secrets/mongo_config.yaml
  tq_conf_file:
    file: secrets/tq_config.yaml
  rohon_conf_file:
    file: secrets/rohon_config.yaml
networks:
  database:
    attachable: true
