version: "3.8"
services:
  app:
    image: galahade/future-trade-docker:latest
    working_dir: /app
    volumes:
      - ".:/app"
    depends_on:
      - mongo
    environment:
      MONGO_CONF_FILE: /run/secrets/mongo_conf_file
      TQ_CONF_FILE: /run/secrets/tq_conf_file
      ROHON_CONF_FILE: /run/secrets/rohon_conf_file
    secrets:
      - mongo_conf_file
      - tq_conf_file
      - rohon_conf_file

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

secrets:
  mongo_conf_file:
    file: secrets/mongo_config.yaml
  tq_conf_file:
    file: secrets/tq_config.yaml
  rohon_conf_file:
    file: secrets/rohon_config.yaml
