version: "3.8"
name:
  future_trading
services:
  app:
    image: galahade/future-trade-docker:v1.1
    working_dir: /app
    networks:
      - future_trading
    environment:
      MONGO_HOST: mongo
      MONGO_ADMINUSERNAME: root
      MONGO_ADMINPASSWORD: example
      MONGO_PORT: 27017

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - trade-mongo-data:/data/db
    networks:
      - future_trading
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  trade-mongo-data:

networks:
  future_trading:
