defaults:
  rules:
    switch_days: &switch_days
      - 20
      - 45
    main_list_1: &main_list_1
      - 1
      - 5
      - 10
    main_list_2: &main_list_2
      - 1
      - 5
      - 9
    main_list_3: &main_list_3
      - 1
      - 3
      - 5
      - 9
    long: &long
      buy_pos_scale: 0.02
      base_scale: 0.02
      stop_loss_scale: 1
      profit_start_scale_1: 3
      promote_scale_1: 6
      promote_target_1: 3
      profit_start_scale_2: 1.5
      promote_scale_2: 3
      promote_target_2: 1
  short: &short
      buy_pos_scale: 0.02
      base_scale: 0.02
      stop_loss_scale: 1
      profit_start_scale: 8
      promote_scale: 3
      promote_target: 1
rules:
  - symbol: KQ.m@SHFE.rb
    is_active: True
    switch_days: *switch_days
    main_list: *main_list_1
    long: *long
    short: *short
  - symbol: KQ.m@DCE.i
    is_active: True
    switch_days: *switch_days
    main_list: *main_list_2
    long:
      <<: *long
      buy_pos_scale: 0.002
    short:
      <<: *short
      buy_pos_scale: 0.002
  - symbol: KQ.m@DCE.p
    is_active: True
    switch_days: *switch_days
    main_list: *main_list_2
    long: *long
    short: *short
  - symbol: KQ.m@DCE.j
    is_active: False
    switch_days: *switch_days
    main_list: *main_list_2
    long:
      <<: *long
      buy_pos_scale: 0.002
    short:
      <<: *short
      buy_pos_scale: 0.002
  - symbol: KQ.m@DCE.jm
    is_active: False
    switch_days: *switch_days
    main_list: *main_list_2
    long:
      <<: *long
      buy_pos_scale: 0.0033
    short:
      <<: *short
      buy_pos_scale: 0.0033
  - symbol: KQ.m@DCE.m
    is_active: False
    switch_days: *switch_days
    main_list: *main_list_2
    long: *long
    short: *short
  - symbol: KQ.m@DCE.y
    is_active: False
    switch_days: *switch_days
    main_list: *main_list_2
    long: *long
    short: *short
  - symbol: KQ.m@DCE.c
    is_active: False
    switch_days: *switch_days
    main_list: *main_list_2
    long: *long
    short: *short
  - symbol: KQ.m@DCE.cs
    is_active: False
    switch_days: *switch_days
    main_list: *main_list_2
    long: *long
    short: *short
  - symbol: KQ.m@DCE.jd
    is_active: False
    switch_days: *switch_days
    main_list: *main_list_2
    long:
      <<: *long
      buy_pos_scale: 0.04
    short:
      <<: *short
      buy_pos_scale: 0.04
  - symbol: KQ.m@DCE.lh
    is_active: False
    switch_days: *switch_days
    main_list: *main_list_3
    long:
      <<: *long
      buy_pos_scale: 0.04
    short:
      <<: *short
      buy_pos_scale: 0.04
  - symbol: KQ.m@DCE.v
    is_active: False
    switch_days: *switch_days
    main_list: *main_list_2
    long:
      <<: *long
      buy_pos_scale: 0.04
    short:
      <<: *short
      buy_pos_scale: 0.04
  - symbol: KQ.m@DCE.eg
    is_active: False
    switch_days: *switch_days
    main_list: *main_list_2
    long: *long
    short: *short
